USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_COBRO_MOD_ESTADO]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_COBRO_MOD_ESTADO] AS'
END
GO

	ALTER PROCEDURE [cent].[AJUSTE_COBRO_MOD_ESTADO]
		  @ID_OPERACION int,
		  @ULTIMO_ESTADO nvarchar(10),
		  @ULTIMO_ESTADO_DESC nvarchar(max),
		  @ULTIMA_RESPUESTA nvarchar(max),
		  @INTENTOS int
	AS
	BEGIN
		SET NOCOUNT ON;
	
	UPDATE [cent].[AJUSTE_CLIENTE_COBRO]
   SET
	  [FECHA_ACTUALIZACION] = getdate()
      ,[ULTIMO_ESTADO] = @ULTIMO_ESTADO
      ,[ULTIMO_ESTADO_DESC] = @ULTIMO_ESTADO_DESC
      ,[ULTIMA_RESPUESTA] = @ULTIMA_RESPUESTA
      ,[INTENTOS] = @INTENTOS
	  ,SERVICIO=0
 WHERE ID_OPERACION=@ID_OPERACION


END
