USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_DEBITO_CUENTAS_DELETE]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_DEBITO_CUENTAS_DELETE] AS'
END
GO

ALTER PROCEDURE [cent].[AJUSTE_DEBITO_CUENTAS_DELETE]
			@CIC varchar(12)
AS 
BEGIN

		DECLARE @TEMP1 INT, @TEMP2 INT

		SELECT @TEMP1 = COUNT(CIC) FROM [cent].[AJUSTE_CLIENTE_COBRO] WHERE CIC = @CIC AND RESTANTE = 0 AND PENDIENTE = 1 AND SERVICIO = 1 AND FECHA_FIN_COBRO >= CONVERT(VARCHAR(8), GETDATE(), 112)
		SELECT @TEMP2 = COUNT(CIC) FROM [cent].[AJUSTE_CLIENTE_COBRO] WHERE CIC = @CIC AND SERVICIO = 1 AND FECHA_FIN_COBRO >= CONVERT(VARCHAR(8), GETDATE(), 112)
	
		IF @TEMP1 = @TEMP2
		BEGIN
			DELETE FROM [cent].[AJUSTE_DEBITO_CUENTAS] WHERE CP_CIC = @CIC
			UPDATE [cent].[AJUSTE_CLIENTE_COBRO] SET  PENDIENTE = 10 WHERE CIC = @CIC AND RESTANTE = 0 AND PENDIENTE = 1 -- PENDIENTE = 10 - REGISTRO ELIMINADO
			SELECT * FROM [cent].AJUSTE_DEBITO_CUENTAS WHERE CP_CIC = @CIC;
		END
		ELSE
		BEGIN
			SELECT * FROM [cent].AJUSTE_DEBITO_CUENTAS WHERE CP_CIC = @CIC;
		END
END;
