USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_CLIENTE_COBRO_X_LOTE_DELETE]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_CLIENTE_COBRO_X_LOTE_DELETE] AS'
END
GO

ALTER PROCEDURE [cent].[AJUSTE_CLIENTE_COBRO_X_LOTE_DELETE]
		    @LOTE nvarchar(max)
		   
AS
BEGIN
	SET NOCOUNT ON;
	
	DELETE [cent].[AJUSTE_CLIENTE_COBRO] WHERE [LOTE]=@LOTE
 

END
