USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_DEBITO_CUENTAS_CTA_GET]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_DEBITO_CUENTAS_CTA_GET] AS'
END
GO

ALTER PROCEDURE [cent].[AJUSTE_DEBITO_CUENTAS_CTA_GET]
	@NRO_CUENTA VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT * FROM [BD_CENTINELA].[cent].[AJUSTE_DEBITO_CUENTAS] WHERE ACCOUNT_NUMBER=@NRO_CUENTA

END
