USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_COBRO_X_CIC_GET]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_COBRO_X_CIC_GET] AS'
END
GO

ALTER PROCEDURE [cent].[AJUSTE_COBRO_X_CIC_GET]
	@CIC	VARCHAR(12)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT * FROM [cent].[AJUSTE_CLIENTE_COBRO]

	WHERE     
		PENDIENTE = 0
		AND FLAG_DEBITO_ABONO=0
		AND LTRIM(RTRIM(CIC)) = LTRIM(RTRIM(@CIC ))
		AND FECHA_FIN_COBRO >= CONVERT(VARCHAR(8), GETDATE(), 112)
		AND SERVICIO=0
		ORDER BY MONTO ASC
END