USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[GET_LIST_CUENTAS_DEBITADO_CODEUDORES_ALS_TRJ]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[GET_LIST_CUENTAS_DEBITADO_CODEUDORES_ALS_TRJ] AS'
END
GO

ALTER PROCEDURE [cent].[GET_LIST_CUENTAS_DEBITADO_CODEUDORES_ALS_TRJ]
AS
BEGIN
	SELECT DISTINCT
		 [ID_CUENTA]
		,[CIC]
		,[CUENTA_ALS] AS CUENTA_AMBOS
		,'NO CORRESPONDE' AS TARJETA_ENCRIPTADA
		,[CUENTA_DEBITO]
		,[ALS_CUENTAS_COBRO_MORA].[MONEDA] AS MONEDA
		,[MONTO]
		,[TIPO_CAMBIO]
		,[GLOSA]
		,[SERVICIO]
		,[ALS_CUENTAS_COBRO_MORA].[ID_OPERACION] AS ID_OPERACION
		,[INTENTO]
		,[REQUEST_BIZTALK]
		,[RESPONSE_BIZTALK]
		,[ALS_CUENTAS_COBRO_MORA].[FECHA_REGISTRO] AS FECHA_REGISTRO
		,[EXTORNO]
		,[COD_EXTORNO]
		,[REQUEST_BIZTALK_EXTORNO]
		,[RESPONSE_BIZTALK_EXTORNO]
		,[FECHA_EXTORNO]
		-- DATOS DE LA TABLA [ALS_TRJ_CTA_PAS_MORA]
		,[DIAS_MORA]
		,[CA_APLICATIVO]
		,[CA_SITUACION]
		,[TIPO_CLIENTE]
		,[CP_APLICATIVO]
	FROM
		[BD_CENTINELA].[cent].[ALS_CUENTAS_COBRO_MORA]
	INNER JOIN [cent].[ALS_TRJ_CTA_PAS_MORA]
		ON [ALS_CUENTAS_COBRO_MORA].CIC = [ALS_TRJ_CTA_PAS_MORA].CP_CIC
		AND [ALS_CUENTAS_COBRO_MORA].CUENTA_DEBITO = [ALS_TRJ_CTA_PAS_MORA].CUENTA
		--AND [ALS_CUENTAS_COBRO_MORA].FECHA_REGISTRO = [ALS_TRJ_CTA_PAS_MORA].FECHA_REGISTRO
	WHERE
		[ALS_TRJ_CTA_PAS_MORA].CA_APLICATIVO = 'ALS' 
		AND [ALS_TRJ_CTA_PAS_MORA].TIPO_CLIENTE = 'CODEUDOR'
		AND CONVERT(DATE, [ALS_CUENTAS_COBRO_MORA].[FECHA_REGISTRO]) = CONVERT(DATE, GETDATE())
UNION
	SELECT DISTINCT
		 [ID_CUENTA]--
		,[CIC]--
		,[CUENTA_ALS]--
		,'NO CORRESPONDE' AS TARJETA_ENCRIPTADA
		,[CUENTA_DEBITO]--
		,[ALS_CUENTAS_COBRO_DIA_0].[MONEDA]--
		,[MONTO]
		,[TIPO_CAMBIO]
		,[GLOSA]
		,[SERVICIO]
		,[ALS_CUENTAS_COBRO_DIA_0].[ID_OPERACION]
		,[INTENTO]
		--,'ALS' AS [SITUACION]
		--,'MORA' AS [NOMBRE_SITUACION]
		--,3 AS [DIAS_MORA]
		,[REQUEST_BIZTALK]
		,[RESPONSE_BIZTALK]
		,[ALS_CUENTAS_COBRO_DIA_0].[FECHA_REGISTRO]--
		,[EXTORNO]
		,[COD_EXTORNO]--
		,[REQUEST_BIZTALK_EXTORNO]
		,[RESPONSE_BIZTALK_EXTORNO]
		,[FECHA_EXTORNO]
		 -- DATOS DE LA TABLA [ALS_TRJ_CTA_PAS_MORA]
		,[DIAS_MORA]
		,[CA_APLICATIVO]
		,[CA_SITUACION]
		,[TIPO_CLIENTE]
		,[CP_APLICATIVO]
	 FROM 
		[BD_CENTINELA].[cent].[ALS_CUENTAS_COBRO_DIA_0]
		INNER JOIN [cent].[ALS_TRJ_CTA_PAS_MORA]
		ON [ALS_CUENTAS_COBRO_DIA_0].CIC = [ALS_TRJ_CTA_PAS_MORA].CP_CIC
		AND [ALS_CUENTAS_COBRO_DIA_0].CUENTA_ALS = [ALS_TRJ_CTA_PAS_MORA].CUENTA
		--AND [ALS_CUENTAS_COBRO_MORA].FECHA_REGISTRO = [ALS_TRJ_CTA_PAS_MORA].FECHA_REGISTRO
	 WHERE
	    [ALS_TRJ_CTA_PAS_MORA].CA_APLICATIVO = 'ALS' 
		AND [ALS_TRJ_CTA_PAS_MORA].TIPO_CLIENTE = 'CODEUDOR'
		AND CONVERT(DATE, [ALS_CUENTAS_COBRO_DIA_0].[FECHA_REGISTRO]) = CONVERT(DATE, GETDATE())
UNION 
	SELECT 
		 [ID_CUENTA]
		,[CIC]--
		,[NZR_CUENTA]--
		,[TARJETA_ENCRIPTADA]
		,[CUENTA_DEBITO]--
		,[TC_CUENTAS_COBRO_MORA].[MONEDA] AS MONEDA
		,[MONTO]--
		,[TIPO_CAMBIO]
		,[GLOSA]--
		,[SERVICIO]
		,[TC_CUENTAS_COBRO_MORA].[ID_OPERACION] AS ID_OPERACION
		,[INTENTO]
		,[REQUEST_BIZTALK]
		,[RESPONSE_BIZTALK]
		,[TC_CUENTAS_COBRO_MORA].[FECHA_REGISTRO] AS FECHA_REGISTRO
		,[EXTORNO]
		,[COD_EXTORNO]--
		,[REQUEST_BIZTALK_EXTORNO]
		,[RESPONSE_BIZTALK_EXTORNO]
		,[FECHA_EXTORNO]
		-- DATOS DE LA TABLA [ALS_TRJ_CTA_PAS_MORA]
		,[DIAS_MORA]
		,[CA_APLICATIVO]
		,[CA_SITUACION]
		,[TIPO_CLIENTE]
		,[CP_APLICATIVO]
	FROM
		[BD_CENTINELA].[cent].[TC_CUENTAS_COBRO_MORA]
		INNER JOIN [cent].[ALS_TRJ_CTA_PAS_MORA]
		ON [TC_CUENTAS_COBRO_MORA].CIC = [ALS_TRJ_CTA_PAS_MORA].CP_CIC
		AND [TC_CUENTAS_COBRO_MORA].CUENTA_DEBITO = [ALS_TRJ_CTA_PAS_MORA].CUENTA
		--AND [ALS_CUENTAS_COBRO_MORA].FECHA_REGISTRO = [ALS_TRJ_CTA_PAS_MORA].FECHA_REGISTRO
	WHERE
		[ALS_TRJ_CTA_PAS_MORA].CA_APLICATIVO = 'TRJ' 
		AND [ALS_TRJ_CTA_PAS_MORA].TIPO_CLIENTE = 'CODEUDOR'
		AND CONVERT(DATE, [TC_CUENTAS_COBRO_MORA].[FECHA_REGISTRO]) = CONVERT(DATE, GETDATE())
UNION
	SELECT 
		 [ID_CUENTA]
		,[CIC]--
		,[NZR_CUENTA]--
		,[TARJETA_ENCRIPTADA]
		,[CUENTA_DEBITO]--
		,[TC_CUENTAS_COBRO_DIA_0].[MONEDA]--
		,[MONTO]--
		,[TIPO_CAMBIO]
		,[GLOSA]--
		,[SERVICIO]
		,[TC_CUENTAS_COBRO_DIA_0].[ID_OPERACION]--
		,[INTENTO]
		,[REQUEST_BIZTALK]
		,[RESPONSE_BIZTALK]
		,[TC_CUENTAS_COBRO_DIA_0].[FECHA_REGISTRO]--
		,[EXTORNO]
		,[COD_EXTORNO]--
		,[REQUEST_BIZTALK_EXTORNO]
		,[RESPONSE_BIZTALK_EXTORNO]
		,[FECHA_EXTORNO]
		-- DATOS DE LA TABLA [ALS_TRJ_CTA_PAS_MORA]
		,[DIAS_MORA]
		,[CA_APLICATIVO]
		,[CA_SITUACION]
		,[TIPO_CLIENTE]
		,[CP_APLICATIVO]
	FROM
		[BD_CENTINELA].[cent].[TC_CUENTAS_COBRO_DIA_0]
		INNER JOIN [cent].[ALS_TRJ_CTA_PAS_MORA]
		ON [TC_CUENTAS_COBRO_DIA_0].CIC = [ALS_TRJ_CTA_PAS_MORA].CP_CIC
		AND [TC_CUENTAS_COBRO_DIA_0].CUENTA_DEBITO = [ALS_TRJ_CTA_PAS_MORA].CUENTA
		--AND [ALS_CUENTAS_COBRO_MORA].FECHA_REGISTRO = [ALS_TRJ_CTA_PAS_MORA].FECHA_REGISTRO
	WHERE
		[ALS_TRJ_CTA_PAS_MORA].CA_APLICATIVO = 'TRJ' 
		AND [ALS_TRJ_CTA_PAS_MORA].TIPO_CLIENTE = 'CODEUDOR'
		AND CONVERT(DATE, [TC_CUENTAS_COBRO_DIA_0].[FECHA_REGISTRO]) = CONVERT(DATE, GETDATE())
	ORDER BY ID_CUENTA DESC
END;