USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_CLIENTE_COBRO_LOTE_X_FECHA_GET]')
			AND type IN (
				N'P'
				,N'PC'
			)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_CLIENTE_COBRO_LOTE_X_FECHA_GET] AS'
END
GO
ALTER PROCEDURE [cent].[AJUSTE_CLIENTE_COBRO_LOTE_X_FECHA_GET]
	@FECHA_INICIO	CHAR(8)
	,@FECHA_FIN	CHAR(8)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
	[LOTE]
	,convert(char(8),[FECHA_REGISTRO],112) as FECHA_REGISTRO
	,[USUARIO_REGISTRO]
	,convert(char(8),[FECHA_APRO_RECH],112) as FECHA_APRO_RECH
	,[USUARIO_APRO_RECH]
	,COUNT([LOTE]) as CANTIDAD_REGISTRO
	,[PENDIENTE]
	
	--CASE 
	--	WHEN [PENDIENTE]=0 THEN 'PENDIENTE PROCESO'
	--	WHEN [PENDIENTE]=1 AND FLAG_DEBITO_ABONO=1 THEN 'ABONO COMPLETADO'
	--	WHEN [PENDIENTE]=1 AND FLAG_DEBITO_ABONO=0 THEN 'DEBITO COMPLETADO'
	--	WHEN [PENDIENTE]=2 THEN 'REGISTRADO'
	--	WHEN [PENDIENTE]=3 THEN 'RECHAZADO'
	-- END AS 'ESTADO'
	
	FROM [cent].[AJUSTE_CLIENTE_COBRO]

	WHERE
	FECHA_REGISTRO >= @FECHA_INICIO
	AND FECHA_REGISTRO <= @FECHA_FIN

	group by [LOTE],convert(char(8),[FECHA_REGISTRO],112),[USUARIO_REGISTRO],convert(char(8),[FECHA_APRO_RECH],112),[USUARIO_APRO_RECH],[PENDIENTE]

END