USE [BD_CENTINELA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (
		SELECT *
		FROM sys.objects
		WHERE object_id = OBJECT_ID(N'[cent].[AJUSTE_COBRO_GET]')
			AND type IN (
				N'P'
				,N'PC'
				)
		)
BEGIN
	EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [cent].[AJUSTE_COBRO_GET] AS'
END
GO

ALTER PROCEDURE [cent].[AJUSTE_COBRO_GET]
	@SERVICIO	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT * FROM [cent].[AJUSTE_CLIENTE_COBRO]

	WHERE     
		PENDIENTE = 0 
	AND SERVICIO = @SERVICIO 
	AND FECHA_FIN_COBRO >= CONVERT(VARCHAR(8), GETDATE(), 112)

END

